### ISSUE TITLE
希望加一个生成到剪贴板的功能

### ISSUE THREAD

**Issue by bytechaocai** [TheFreeOne/Java-Bean-To-Ts-Interface#2]
目前只能生成到文件，希望将来可以生成到剪贴板，就像idea里数据库工具这样

![图片](https://github.com/TheFreeOne/Java-Bean-To-Ts-Interface/assets/39870481/f92c1f59-7c7f-4360-906b-316c1dcfe7e1)

前两行是生成到剪贴板，第三行是生成到文件。

今天写代码看到两个vo类要转成ts里的接口，头大，虽然可以用正则表达式提升转换效率，但是依然很麻烦，就搜了一下，搜到了老铁的工具，感谢老铁解放我的双手，提升我的效率，节省我的时间

**Comment by TheFreeOne** [comment]
额，0.0.9已经提交，新增了复制到剪切板和在textarea编辑的功能，你可以待审核通过之后idea plugin提示更新的时候更新后使用，或者到gitee同名仓库中下载
